# Generated by Django 4.2.1 on 2023-06-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0002_rename_role_detallepermiso_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepermiso',
            old_name='roleId',
            new_name='role',
        ),
    ]
