# Generated by Django 4.2.1 on 2023-06-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0003_rename_roleid_detallepermiso_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepermiso',
            old_name='role',
            new_name='roleId',
        ),
    ]
