# Generated by Django 4.2.1 on 2023-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0004_alter_user_document_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='order',
            name='statu',
            field=models.CharField(default='Por Pagar', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
