# Generated by Django 4.2.2 on 2023-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0004_rename_role_detallepermiso_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='statu',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Por Pagar', max_length=50),
        ),
    ]
