# Generated by Django 4.2.2 on 2023-06-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0005_remove_order_statu_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='order',
            new_name='orderid',
        ),
    ]
