# Generated by Django 4.2.2 on 2023-06-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0006_rename_order_detail_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentorder',
            old_name='order',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='orderid',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.supplies'),
        ),
    ]
