# Generated by Django 4.2 on 2023-06-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0007_alter_order_user_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepermiso',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.permission', to_field='module_name'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
