# Generated by Django 4.2.2 on 2023-06-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0007_rename_order_contentorder_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentorder',
            name='supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.supplies', to_field='name'),
        ),
    ]
