# Generated by Django 4.2.1 on 2023-07-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
    ]
