# Generated by Django 4.2 on 2023-06-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0010_alter_detallepermiso_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepermiso',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.role', to_field='name'),
        ),
    ]
