# Generated by Django 4.2.1 on 2023-07-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0010_remove_role_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepermiso',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourburger.permission', to_field='module_name'),
        ),
        migrations.AlterField(
            model_name='detallepermiso',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourburger.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yourburger.role'),
        ),
    ]
