# Generated by Django 4.2.1 on 2023-07-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0011_alter_detallepermiso_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepermiso',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.permission', to_field='module_name'),
        ),
    ]
