# Generated by Django 4.2 on 2023-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0011_alter_detallepermiso_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(through='yourburger.DetallePermiso', to='yourburger.permission'),
        ),
    ]
