# Generated by Django 4.2.1 on 2023-07-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0012_alter_detallepermiso_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepermiso',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.role'),
        ),
    ]
