# Generated by Django 4.2 on 2023-06-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0008_remove_content_name_content_supplies_products_image_and_more'),
        ('yourburger', '0012_role_permissions'),
    ]

    operations = [
    ]
