# Generated by Django 4.2.2 on 2023-08-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0014_alter_content_product_alter_content_supplies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourburger.products'),
        ),
    ]
