# Generated by Django 4.2.2 on 2023-08-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourburger', '0015_alter_content_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='price',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='stock',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
